# Generated by Django 6.0.7 on 2026-07-16 14:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClauseFinding',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('clause_text', models.TextField()),
                ('risk_level', models.CharField(choices=[('merah', 'Merah'), ('kuning', 'Kuning'), ('hijau', 'Hijau')], max_length=16)),
                ('plain_language_summary', models.TextField()),
                ('legal_reference', models.JSONField(null=True)),
                ('order_index', models.PositiveIntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='documents.document')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('extraction_started', 'Extraction Started'), ('extraction_done', 'Extraction Done'), ('clause_flagged', 'Clause Flagged'), ('mcp_validated', 'Mcp Validated'), ('mcp_validation_failed', 'Mcp Validation Failed'), ('audit_completed', 'Audit Completed'), ('audit_failed', 'Audit Failed')], max_length=32)),
                ('payload', models.JSONField()),
                ('sequence_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='documents.document')),
            ],
            options={
                'ordering': ['document', 'sequence_number'],
                'constraints': [models.UniqueConstraint(fields=('document', 'sequence_number'), name='unique_seq_per_doc')],
            },
        ),
    ]
