# Generated by Django 6.0.7 on 2026-07-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clausefinding',
            name='category',
            field=models.CharField(default='default', max_length=64),
        ),
        migrations.AddField(
            model_name='clausefinding',
            name='clause_safety_score',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('extraction_started', 'Extraction Started'), ('extraction_done', 'Extraction Done'), ('clause_flagged', 'Clause Flagged'), ('mcp_validated', 'Mcp Validated'), ('mcp_validation_failed', 'Mcp Validation Failed'), ('score_computed', 'Score Computed'), ('visualization_generated', 'Visualization Generated'), ('recommendation_generated', 'Recommendation Generated'), ('draft_generated', 'Draft Generated'), ('audit_completed', 'Audit Completed'), ('audit_failed', 'Audit Failed')], max_length=32),
        ),
        migrations.AlterField(
            model_name='clausefinding',
            name='risk_level',
            field=models.CharField(choices=[('hijau_tua', 'Hijau Tua'), ('hijau_muda', 'Hijau Muda'), ('kuning', 'Kuning'), ('merah_muda', 'Merah Muda'), ('merah_tua', 'Merah Tua')], max_length=16),
        ),
    ]
