# Generated by Django 6.0.7 on 2026-07-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_clausefinding_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clausefinding',
            name='is_fatal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clausefinding',
            name='s1_score',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='clausefinding',
            name='s2_score',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='clausefinding',
            name='s3_score',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='clausefinding',
            name='clause_safety_score',
            field=models.FloatField(default=3.0),
        ),
    ]
