# Generated by Django 6.0.7 on 2026-07-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0003_clausefinding_is_fatal_clausefinding_s1_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clausefinding',
            name='mcp_query_hint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clausefinding',
            name='risky_keywords',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clausefinding',
            name='legal_reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clausefinding',
            name='order_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clausefinding',
            name='plain_language_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
