# Generated by Django 6.0.7 on 2026-07-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0004_clausefinding_mcp_query_hint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clausefinding',
            name='s1_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clausefinding',
            name='s2_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clausefinding',
            name='s3_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
