# Generated by Django 6.0.7 on 2026-08-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='extra_document_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
