# Generated by Django 6.0.7 on 2026-08-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='plan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
