# Generated by Django 6.0.7 on 2026-07-16 16:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audits', '0002_clausefinding_category_and_more'),
        ('documents', '0002_document_overall_risk_score_document_score_breakdown_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('negotiate', 'Negotiate'), ('reject', 'Reject'), ('request_clarification', 'Request Clarification'), ('accept_with_condition', 'Accept With Condition'), ('seek_legal_aid', 'Seek Legal Aid')], max_length=24)),
                ('priority', models.CharField(choices=[('tinggi', 'Tinggi'), ('sedang', 'Sedang'), ('rendah', 'Rendah')], max_length=8)),
                ('recommendation_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clause', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='audits.clausefinding')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='ContractVisualization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scenario_type', models.CharField(choices=[('financial_loss', 'Financial Loss'), ('clause_impact', 'Clause Impact'), ('before_after', 'Before After')], max_length=16)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clause', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visualizations', to='audits.clausefinding')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizations', to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedContractDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('draft_type', models.CharField(choices=[('full_rewrite', 'Full Rewrite'), ('clause_patch', 'Clause Patch')], max_length=16)),
                ('content', models.JSONField()),
                ('disclaimer', models.TextField(default='Draf ini dihasilkan otomatis oleh AI sebagai bahan negosiasi awal dan BUKAN pengganti nasihat hukum profesional. Konsultasikan dengan advokat sebelum menandatangani kontrak final.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='documents.document')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
