name: Trigger auto deployment for celery-kupaskontrak

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/celery-kupaskontrak-AutoDeployTrigger-9b53c42c-c4a0-4efb-9a8c-374a19c43324.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CELERYKUPASKONTRAK_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CELERYKUPASKONTRAK_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CELERYKUPASKONTRAK_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server
          registryUrl: docker.io
          registryUsername: ${{ secrets.CELERYKUPASKONTRAK_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CELERYKUPASKONTRAK_REGISTRY_PASSWORD }}
          containerAppName: celery-kupaskontrak
          resourceGroup: rg-kupaskontrak
          imageToBuild: renhartoz/celery-kupaskontrak:${{ github.sha }}


