# Generated by Django 6.0.7 on 2026-07-16 14:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cloudinary_public_id', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('native', 'Native PDF'), ('scanned', 'Scanned PDF')], max_length=16, null=True)),
                ('page_count', models.PositiveIntegerField(null=True)),
                ('file_size_bytes', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('extracting', 'Extracting'), ('analyzing', 'Analyzing'), ('validating_mcp', 'Validating Mcp'), ('done', 'Done'), ('failed', 'Failed')], default='uploaded', max_length=24)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'status'], name='documents_d_owner_i_683479_idx')],
            },
        ),
    ]
