# Generated by Django 6.0.7 on 2026-07-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='overall_risk_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='score_breakdown',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('extracting', 'Extracting'), ('analyzing', 'Analyzing'), ('validating_mcp', 'Validating Mcp'), ('generating_insights', 'Generating Insights'), ('done', 'Done'), ('failed', 'Failed')], default='uploaded', max_length=24),
        ),
    ]
