# Generated by Django 6.0.7 on 2026-07-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_overall_risk_score_document_score_breakdown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
